### ISSUE TITLE
Stepping in event mode freezes tscript

### ISSUE THREAD

**Issue by manuel-fischer** [TGlas/tscript#13] opened 2019-12-12 17:29 UTC
When stepping into `enterEventMode()` or out of an eventhandler with the following buttons, the IDE freezes completely:

![Run current line, step out of function](https://user-images.githubusercontent.com/58823087/70733802-51a78400-1d0b-11ea-8c2a-e18764d34d0c.png)

**Example code**

```
setEventHandler("timer", function(event) {
    print("timer");
});

enterEventMode();
```

**Comment by TGlas** [comment] 2019-12-12 19:46
Thanks for the report, the problem is now fixed.

**Closed by TGlas** 2019-12-12 19:46 UTC
